# https://hub.docker.com/r/confluentinc/confluent-local
# Variables - https://github.com/confluentinc/kafka-images/blob/7.4.x/local/include/etc/confluent/docker/configureDefaults
version: '2'
services:
  kafka-broker:
    image: confluentinc/confluent-local:7.4.1
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "8082:8082"
      - "9093:9093"
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"
      - "9101:9101"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,CONNECTION_FROM_HOST_SSL:SSL
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092,SSL://kafka-broker:29093,CONNECTION_FROM_HOST_SSL://localhost:9093'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker:29095'
      KAFKA_SSL_TRUSTSTORE_FILENAME: 'server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: 'kafka_credentials'
      KAFKA_SSL_KEYSTORE_FILENAME: 'server.keystore.jks'
      KAFKA_SSL_KEYSTORE_CREDENTIALS: 'kafka_credentials'
      KAFKA_SSL_KEY_CREDENTIALS: 'kafka_credentials'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29095,PLAINTEXT_HOST://localhost:9092,SSL://kafka-broker:29093,CONNECTION_FROM_HOST_SSL://localhost:9093'
      # KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      
    volumes:
      - ./certs:/etc/kafka/secrets

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9999:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:29092